package gui;

/**
 * This panel holds the information for what kind of die is being measured and
 * how many instances have been found.
 *
 * @author Eben Howard
 */
public class CountingPanel extends javax.swing.JPanel {

    private int count = 0, max = 1;

    /**
     * Creates new form CountingPanel
     */
    public CountingPanel() {
        initComponents();
        countingBar.setMaximum(max);
        countingBar.setStringPainted(true);
    }

    public void increaseScale() {
        max *= 2;
        countingBar.setMaximum(max);
    }

    /**
     * Sets the label to the outcome being counted.
     *
     * @param name
     */
    public void setOutcomeName(String name) {
        outcomeName.setText(name);
    }

    /**
     * Adds one to the count of this outcome. Rescales the bar if this would
     * overflow its current size.
     *
     * @return true if the bar was rescaled
     */
    public boolean addCount() {
        count++;
        if (count > max) {
            increaseScale();
            return true;
        }
        countingBar.setValue(count);
        countingBar.setString("" + count);
        return false;
    }

    /**
     * Returns the total number counted.
     *
     * @return
     */
    public int getTotal() {
        return count;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        countingBar = new javax.swing.JProgressBar();
        outcomeName = new javax.swing.JLabel();

        countingBar.setForeground(new java.awt.Color(153, 0, 0));
        countingBar.setMaximum(10);
        countingBar.setFocusable(false);

        outcomeName.setText("Dice");
        outcomeName.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outcomeName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countingBar, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outcomeName)
            .addComponent(countingBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar countingBar;
    private javax.swing.JLabel outcomeName;
    // End of variables declaration//GEN-END:variables
}
