package gui;

/**
 * This panel contains the total number of rolls made and the current scale
 * factor.
 *
 * @author Eben Howard
 */
public class TotalsPanel extends javax.swing.JPanel {

    private int rolls = 0, scale = 1;

    /**
     * Creates new form TotalsPanel
     */
    public TotalsPanel() {
        initComponents();
    }

    public void addRoll() {
        rolls++;
        totalRolls.setText("" + rolls);
    }

    /**
     * Doubles the current scale and redraws the measurement bar.
     */
    public void increaseScale() {
        scale *= 2;
        scaleMax.setText("" + scale);
    }

    public void setCounted(int count) {
        diceCounted.setText("" + count);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalRolls = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scaleMax = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        diceCounted = new javax.swing.JLabel();

        jLabel1.setText("Number of Rolls:");

        totalRolls.setText("0");

        jLabel2.setText("Scale Maximum:");

        scaleMax.setText("10");

        jLabel3.setText("Number of Dice Counted:");

        diceCounted.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scaleMax)
                    .addComponent(totalRolls)
                    .addComponent(diceCounted))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalRolls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(diceCounted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(scaleMax))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diceCounted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel scaleMax;
    private javax.swing.JLabel totalRolls;
    // End of variables declaration//GEN-END:variables
}
